services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      # required to access the UI on all interfaces; default is localhost
      - CLI_ARGS=--webservice-interface=0.0.0.0
      - DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES=duplicati.home;10.10.10.5;localhost;*
    env_file:
      - ./duplicati.env
    volumes:
      # config and database
      - /opt/data/duplicati/config:/config
      # source data to back up
      - /opt/data/homeassistant:/source/homeassistant
      - /opt/data/esphome:/source/esphome
      - /opt/data/portainer:/source/portainer
      - /opt/data/traefik:/source/traefik
      - /opt/data/uptime-kuma:/source/uptime-kuma
      - /opt/stacks:/source/stacks
      # mount your NAS (see below) to /backup in the container
      - /mnt/nas/backup:/backup
    networks:
      - edge
    #ports:
    #  - "8200:8200"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.home`)"
      #- "traefik.http.routers.duplicati.middlewares=secured@file" # optional, add if you have a middleware for authentication
      - "traefik.http.routers.duplicati.middlewares=lan-only@file"
      #- "traefik.http.routers.duplicati.entrypoints=web" # only web, no websecure
      - "traefik.http.routers.duplicati.tls=true" # disable TLS for this router
      - "traefik.http.routers.duplicati.entrypoints=websecure" # disable websecure entrypoint
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"

networks:
  edge:
    external: true